# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osiris < Formula
  desc ""
  homepage "https://github.com/Voldemat/osiris"
  version "0.7.2"

  on_macos do
    url "https://github.com/Voldemat/osiris/releases/download/0.7.2/osiris_0.7.2_darwin_all.tar.gz"
    sha256 "a6bb3a4ea86d7661120f731106a56810f33e4c2e9ff62b1d1d60a064c0486caf"

    def install
      bin.install "osiris"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Voldemat/osiris/releases/download/0.7.2/osiris_0.7.2_linux_arm64.tar.gz"
      sha256 "29fe08991086ba46b558f8feeb220c486930b44fbff3433603fc92415eba3d89"

      def install
        bin.install "osiris"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Voldemat/osiris/releases/download/0.7.2/osiris_0.7.2_linux_amd64.tar.gz"
      sha256 "957b3874b3a1e047c5b41e7d0323ce753460d6226037eaad28497fa335047d85"

      def install
        bin.install "osiris"
      end
    end
  end
end
