# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Osiris < Formula
  desc ""
  homepage "https://github.com/Voldemat/osiris"
  version "0.7.7"

  on_macos do
    url "https://github.com/Voldemat/osiris/releases/download/0.7.7/osiris_0.7.7_darwin_all.tar.gz"
    sha256 "614070ffc4a41a6f17fb25c816e24cb4fb22608c0a27250bb9be991c77f5efda"

    def install
      bin.install "osiris"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Voldemat/osiris/releases/download/0.7.7/osiris_0.7.7_linux_arm64.tar.gz"
      sha256 "cde6927160ab9a579cf39c63457c21f60c9f5060a6a48592346a4d5ce35c7499"

      def install
        bin.install "osiris"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Voldemat/osiris/releases/download/0.7.7/osiris_0.7.7_linux_amd64.tar.gz"
      sha256 "059867986274996bf91a43f69a6ebb3a324f917f7f673d5a940a6e07d71359cc"

      def install
        bin.install "osiris"
      end
    end
  end
end
